### ISSUE TITLE
Add secondary modifiers which can be applied on the Schema quantities 

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/generic-catalog-reader#3]
As a user, it would be very convenient if I could add my own modifiers which can be applied on the standard fields defined in the DESC Schema, without any knowledge of the native format.
Simple example, I want to simulate some photometric redshifts using the following:
```
catalog.add_quantity_modifier('redshift_photometric', (lambda x: x + sigma * (1+x) *randn(len(x)), 'redshift'))
```
This fails with the following:
```
ValueError: Native quantity `redshift` does not exist (required by `redshift_photometric`)
```

**Comment by yymao** [comment]
I added a new method `add_modifier_on_derived_quantities` to address this issue. Try the following:

```python
def add_photometric_error(z, sigma=0.01):
    return x + sigma * (1.0+x) * np.random.randn(*x.shape)
catalog.add_modifier_on_derived_quantities('redshift_photometric', add_photometric_error, 'redshift')
catalog.get_quantities('redshift_photometric')
```

Note that for secondary modifiers, there must be a callable (i.e., one **cannot** just rename quantities). To rename, one should do:
```python
catalog.add_quantity_modifier('new_name', catalog.get_quantity_modifier('old_name'))
```

**Comment by yymao** [comment]
@EiffL Please see if this satisfies your need. Close this issue if so. Thanks!

**Comment by EiffL** [comment]
Yes, that is exactly what I needed. Thanks !
